// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3xNYR32kFHkFoA2HtKCJ9-hiJUVQqUUY',
    appId: '1:455983045676:web:e3372981cece924b6e0589',
    messagingSenderId: '455983045676',
    projectId: 'vetclinic-3d458',
    authDomain: 'vetclinic-3d458.firebaseapp.com',
    storageBucket: 'vetclinic-3d458.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsvWwT2JKoplZwocREeMmYmE8rN2huMIU',
    appId: '1:455983045676:android:4aa8e0de5dedf93b6e0589',
    messagingSenderId: '455983045676',
    projectId: 'vetclinic-3d458',
    storageBucket: 'vetclinic-3d458.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ8ZDix2mZ5qarMcu86FoFbxx3SMny7rs',
    appId: '1:455983045676:ios:ea94d955ed21e1536e0589',
    messagingSenderId: '455983045676',
    projectId: 'vetclinic-3d458',
    storageBucket: 'vetclinic-3d458.firebasestorage.app',
    iosBundleId: 'com.example.vetClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3xNYR32kFHkFoA2HtKCJ9-hiJUVQqUUY',
    appId: '1:455983045676:web:8ee82582e8ee24a06e0589',
    messagingSenderId: '455983045676',
    projectId: 'vetclinic-3d458',
    authDomain: 'vetclinic-3d458.firebaseapp.com',
    storageBucket: 'vetclinic-3d458.firebasestorage.app',
  );
}
